db:
  image: postgres
  volumes:
    - ./data/postgresql:/var/lib/postgresql/data

uwsgi:
  restart: always
  image: mso4sc/sregistry
  volumes:
    - ./app:/code
    - ./data/static:/var/www/static
    - ./data/images:/var/www/images
  links:
    - redis
    - db

nginx:
  restart: always
  image: nginx
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ./data/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    - ./data/nginx/uwsgi_params.par:/etc/nginx/uwsgi_params.par:ro
    - ./data/ssl/certs:/etc/ssl/certs:ro
    - ./data/ssl/private:/etc/ssl/private:ro
  volumes_from:
    - uwsgi
  links:
    - uwsgi
    - db

redis:
  restart: always
  image: redis:latest
  volumes:
    - ./data/redis:/data
  expose:
    - "6379"


worker:
  image: mso4sc/sregistry
  command: celery worker -A shub.celery -Q default -n default@%h -B
  volumes:
    - ./app:/code
  volumes_from:
    - uwsgi
  links:
    - redis
    - db
